biogrid:
    access_key: "931d2c261ab610818b96bbd8c2175fa7"
    base_url: "https://webservice.thebiogrid.org"
jaspar:
    base_url: "https://jaspar.genereg.net"
pfam:
    base_url: "https://pfam.xfam.org/"
uscs:
    base_url: 'https://api.genome.ucsc.edu/'
#https://github.com/Ensembl/ensembl-rest/wiki/Getting-Started
ensembl_biomart:
    base_url: 'http://rest.ensembl.org/'
